"""empty message

Revision ID: 10830a1c4f34
Revises: d6c69844a82d
Create Date: 2026-01-10 10:58:43.836345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10830a1c4f34'
down_revision = 'd6c69844a82d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
